# Generated by Django 2.0.8 on 2019-07-22 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='parent_msg',
            field=models.ForeignKey(blank=True, null=True, on_delete='SET_NULL', related_name='next_messages', to='message.Message', verbose_name='Parent message'),
        ),
    ]
