# Generated by Django 2.0.8 on 2019-07-22 04:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0002_auto_20190722_1321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='parent_msg',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next_messages', to='message.Message', verbose_name='Parent message'),
        ),
    ]
