# Generated by Django 2.2.3 on 2019-08-09 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0002_auto_20190805_2054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='subject',
            field=models.CharField(max_length=140, null=True, verbose_name='Subject'),
        ),
    ]
