# Generated by Django 2.2.10 on 2020-03-30 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20200331_0033'),
    ]

    operations = [
        migrations.AddField(
            model_name='customeruser',
            name='message_count',
            field=models.IntegerField(default=0),
        ),
    ]
