# Generated by Django 2.2.3 on 2019-08-05 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20190805_1934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customeruser',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customeruser',
            name='email',
            field=models.EmailField(blank=True, max_length=254, unique=True),
        ),
    ]
