# Generated by Django 2.2.3 on 2019-07-15 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20190716_0120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customeruser',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
